version: '3.7'

services:

    selenium_chrome:
        image: selenium/standalone-chrome
        container_name: selenium_chrome
        networks:
          - pyselenium-net
        volumes:
          - /dev/shm:/dev/shm
        ports:
          - "4444:4444"
          - "5900:5900"

    selenium_firefox:
        image: selenium/standalone-firefox:latest
        container_name: selenium_firefox
        networks:
          - pyselenium-net
        volumes:
          - /dev/shm:/dev/shm
        ports:
          - "4444:4444"
          - "5900:5900"

    py_tests_chrome:
        build:  .
        depends_on:
          - selenium_chrome
        networks:
          - pyselenium-net
        volumes:
          - ./test_results/allure_results:/app/test_results/allure_results
          - .:/app
        command: "pytest -s tests/ --host selenium_chrome --port 4444 --alluredir=test_results/allure_results/"

    py_tests_firefox:
        build:  .
        depends_on:
          - selenium_firefox
        networks:
          - pyselenium-net
        volumes:
          - ./test_results/allure_results:/app/test_results/allure_results
          - .:/app
        command: "pytest -s tests/ --browser firefox --host selenium_firefox --port 4444 --alluredir=test_results/allure_results/"

    py_tests_chrome_smoke:
        build:  .
        depends_on:
          - selenium_chrome
        networks:
          - pyselenium-net
        volumes:
          - ./test_results/allure_results:/app/test_results/allure_results
          - .:/app
        command: "pytest -s -m smoke --host selenium_chrome --port 4444 --alluredir=test_results/allure_results/"

    py_tests_firefox_smoke:
        build:  .
        depends_on:
          - selenium_firefox
        networks:
          - pyselenium-net
        volumes:
          - ./test_results/allure_results:/app/test_results/allure_results
          - .:/app
        command: "pytest -s -m smoke --browser firefox --host selenium_firefox --port 4444 --alluredir=test_results/allure_results/"

networks:
    pyselenium-net:
      driver: bridge